name: test

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo "✅ Workflow déclenché depuis ${{ github.ref }}"
